# Generated by Django 5.2.4 on 2025-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ganhador_cpf',
            field=models.CharField(blank=True, help_text='CPF do ganhador.', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='quantidade_numeros',
            field=models.PositiveIntegerField(default=100, help_text='Quantidade total de números disponíveis para esta rifa.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
