# Generated by Django 5.2.4 on 2025-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0008_rifa_ganhador_cpf_rifa_quantidade_numeros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='quantidade_numeros',
            field=models.PositiveIntegerField(default=100, help_text='Quantidade total de números disponíveis para esta rifa.'),
        ),
        migrations.AddField(
            model_name='rifa',
            name='ganhador_cpf',
            field=models.CharField(blank=True, help_text='CPF do ganhador.', max_length=14, null=True),
        ),
    ]
