# Generated by Django 5.2.4 on 2025-08-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0011_premiobilhete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiobilhete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
