# Generated by Django 5.2.4 on 2025-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0012_alter_premiobilhete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_qr_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
