# Generated by Django 5.2.4 on 2025-09-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('rifa', '0009_pedido'),
        ('rifa', '0013_pedido_mercado_pago_payment_id_pedido_pix_qr_base64'),
    ]

    operations = [
    ]
