# Generated by Django 5.2.6 on 2025-09-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0017_aumentar_quantidade_numeros'),
        ('rifa', '0018_numero_reservado_em'),
    ]

    operations = [
    ]
