# Generated by Django 5.2.6 on 2025-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0019_merge_20250928_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='quantidade_numeros',
            field=models.PositiveIntegerField(default=100, help_text='Quantidade total de números disponíveis para esta rifa.'),
        ),
    ]
